In [137]:
# #To be run in further steps
# import gensim.downloader 
# import ast

# # Show all available models in gensim-data
# print(list(gensim.downloader.info()['models'].keys()))
# model = gensim.downloader.load('word2vec-google-news-300')

In [138]:
import pandas as pd
import numpy as np
import re
import nltk
import spacy
import string

In [139]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [140]:
!cp gdrive/MyDrive/GitHub/NLP-project-/preprocessing_functions.py .

In [157]:
!python preprocessing_functions.py

In [142]:
#df = pd.read_csv('NLP_project_kickoff_data.csv', encoding='utf-8')
df = pd.read_csv('NLP_project_kickoff_data.csv', encoding='utf-8')

In [162]:
df.head()

   Unnamed: 0  ...                          biography_wo_stopfreqrare
0           0  ...                                                nan
1           1  ...  facial cosmetics, ent thyroid clinic mr. mrina...
2           2  ...  facial cosmetics, ent thyroid clinic mr. mrina...
3           3  ...  facial cosmetics, ent thyroid clinic mr. mrina...
4           4  ...  ðÿœ� london, uk ðÿ�¥ co-founder @theplasticsur...

[5 rows x 29 columns]

In [144]:
df_emo= pd.read_csv('emojis.csv')

##Emoji replacement

In [146]:
for col in df.columns:
  #print(type(col))
  if type(col)=="<class 'str'>":
    emojis_replacement(col)  
  #  lower_column(col)

##Text Lower

In [147]:
lower_column('biography')
lower_column('caption')
lower_column('tokens')

##Remove punctuation

In [ ]:
df.head()

In [152]:
df["biography_wo_punc"] = df["biography"].apply(lambda text: remove_punctuation(text))
#df["caption_wo_punc"] = df["caption"].apply(lambda text: remove_punctuation(text)) #not working
#df["profile_name"] = df["profile_name"].apply(lambda text: remove_punctuation(text)) #not working
#df["tokens_wo_punc"] = df["tokens"].apply(lambda text: remove_punctuation(text))


df.head()

AttributeError: ignored

In [ ]:
pip install --upgrade nltk

In [ ]:
pip install  --upgrade gensim --pre

In [ ]:
!pip install --upgrade gensim

In [ ]:
import nltk
nltk.download('stopwords')

In [153]:
df["biography_wo_stop"] = df["biography"].apply(lambda text: remove_stopwords(text))
df.head()

   Unnamed: 0  ...                                  biography_wo_stop
0           0  ...                                                nan
1           1  ...  facial cosmetics, ent thyroid clinic mr. mrina...
2           2  ...  facial cosmetics, ent thyroid clinic mr. mrina...
3           3  ...  facial cosmetics, ent thyroid clinic mr. mrina...
4           4  ...  ðÿœ� london, uk ðÿ�¥ co-founder @theplasticsur...

[5 rows x 27 columns]

#Removal of frequent words

In [154]:
from collections import Counter
cnt = Counter()
for text in df["biography_wo_stop"].values:
    for word in text.split():
        cnt[word] += 1
        
cnt.most_common(10)

[('&', 166),
 ('based', 128),
 ('home', 112),
 ('enhancing', 104),
 ('ð�—¡ð�—®ð�˜�ð�˜‚ð�—¿ð�—®ð�—¹', 104),
 ('ð�—•ð�—²ð�—®ð�˜‚ð�˜�ð�˜†', 104),
 ('ðÿœ¥', 104),
 ('@officialnavyprofessional', 104),
 ('educator-', 104),
 ('discount', 104)]

In [156]:
FREQWORDS = set([w for (w, wc) in cnt.most_common(10)])
# def remove_freqwords(text):
#     """custom function to remove the frequent words"""
#     return " ".join([word for word in str(text).split() if word not in FREQWORDS])

df["biography_wo_stopfreq"] = df["biography_wo_stop"].apply(lambda text: remove_freqwords(text))
df.head()

   Unnamed: 0  ...                              biography_wo_stopfreq
0           0  ...                                                nan
1           1  ...  facial cosmetics, ent thyroid clinic mr. mrina...
2           2  ...  facial cosmetics, ent thyroid clinic mr. mrina...
3           3  ...  facial cosmetics, ent thyroid clinic mr. mrina...
4           4  ...  ðÿœ� london, uk ðÿ�¥ co-founder @theplasticsur...

[5 rows x 28 columns]

#removal of rare words

In [ ]:

n_rare_words = 10
RAREWORDS = set([w for (w, wc) in cnt.most_common()[:-n_rare_words-1:-1]])

In [158]:
df["biography_wo_stopfreqrare"] = df["biography_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
df.head()

   Unnamed: 0  ...                          biography_wo_stopfreqrare
0           0  ...                                                nan
1           1  ...  facial cosmetics, ent thyroid clinic mr. mrina...
2           2  ...  facial cosmetics, ent thyroid clinic mr. mrina...
3           3  ...  facial cosmetics, ent thyroid clinic mr. mrina...
4           4  ...  ðÿœ� london, uk ðÿ�¥ co-founder @theplasticsur...

[5 rows x 29 columns]

#Stemming

In [ ]:
# from nltk.stem.porter import PorterStemmer

# stemmer = PorterStemmer()
# def stem_words(text):
#     return " ".join([stemmer.stem(word) for word in text.split()])

In [161]:
df["biography_stemmed"] = df["biography_wo_punc"].apply(lambda text: stem_words(text))
df.head()

KeyError: ignored

In [ ]:
from nltk.stem.snowball import SnowballStemmer
SnowballStemmer.languages

('arabic',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'hungarian',
 'italian',
 'norwegian',
 'porter',
 'portuguese',
 'romanian',
 'russian',
 'spanish',
 'swedish')

#Lemmatization

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

True

In [160]:
from nltk.stem import WordNetLemmatizer

# lemmatizer = WordNetLemmatizer()
# def lemmatize_words(text):
#     return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["biography_lemm"] = df["biography_stemmed"].apply(lambda text: lemmatize_words(text))
df.head()

KeyError: ignored

#Removal of URLs

In [159]:
df['biography_wo_urls']=df['biography_lemm'].apply(remove_urls)
df

KeyError: ignored

#Removal of HTML tags

In [ ]:
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)

print(remove_html(text))

Lcomputer Liphone Lmusic8 Lgame2 âš½â˜•ðŸ»ðŸ•