In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
!cp gdrive/MyDrive/GitHub/NLP-project-/preprocessing_functions.py .

In [4]:
import pandas as pd
import numpy as np
import re
import nltk
import spacy
import string
import preprocessing_functions

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

In [5]:
!python preprocessing_functions.py

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [6]:
execfile('preprocessing_functions.py')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

#Text pre-processing

In [8]:
#df = pd.read_csv('NLP_project_kickoff_data.csv', encoding='utf-8')
#df = pd.read_csv('Instagram.csv', encoding='utf-8')
df=pd.read_csv('Instagram_profile_20220220_172954.success.csv', encoding='utf-8', sep=',')
df

#df_emo= pd.read_csv('emojis.csv')

,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,likes,media_type,posts_count,followers,is_verified,datetime,image_url,url,comments,thumbnails,location
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,üåéüß≥üî•ü•áüé®üç∑‚òï\n üáªüá™ üá®üá¥\nEMPRESARIO SO√ëADOR\...,3.654414e+09,NaN,NaN,1105.0,NaN,NaN,515.0,1244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,NaN,NaN,8.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44154,drdariushnikkhah,Finalising the 50 chapters of an exciting book...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,"Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...",2.648973e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,137.0,Image,136.0,1124.0,NaN,1.630002e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTDCnYcqSBP/,6.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom"
44155,drdariushnikkhah,At Harefield heart ‚ù§Ô∏è hospital - probably only...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,"Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...",2.647971e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,83.0,Image,136.0,1124.0,NaN,1.629883e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS_e1ntq-Qo/,3.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....",NaN
44156,drdariushnikkhah,Great to be back at the first face to face sci...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,"Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...",2.659552e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,75.0,Carousel,136.0,1124.0,NaN,1.631263e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTooI4TK0sF/,0.0,"[{""src"":""https://scontent-lhr8-1.cdninstagram....","Oxford, Oxfordshire"
44157,drdariushnikkhah,Before and after of a bilateral breast reducti...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,"Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...",2.646593e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,77.0,Image,136.0,1124.0,NaN,1.629718e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS6lisWKX4k/,7.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom"
44158,drdariushnikkhah,Local anaesthetic flexor tendon repair is a sa...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
percent_missing = df.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'column_name': df.columns,'percent_missing': percent_missing})
missing_value_df

                           column_name  percent_missing
account                        account         0.092846
caption                        caption         0.695215
profile_name              profile_name         0.267216
profile_image_link  profile_image_link         0.092846
biography                    biography         0.799384
id                                  id         0.036233
business_email          business_email       100.000000
external_url              external_url         3.172626
following                    following         0.036233
likes                            likes         0.095111
media_type                  media_type         0.095111
posts_count                posts_count         0.036233
followers                    followers         0.036233
is_verified                is_verified        86.863380
datetime                      datetime         0.095111
image_url                    image_url         0.095111
url                                url         0.095111
comments                      comments         0.095111
thumbnails                  thumbnails         0.095111
location                      location        50.533300

In [10]:
df.dtypes

account                object
caption                object
profile_name           object
profile_image_link     object
biography              object
id                    float64
business_email        float64
external_url           object
following             float64
likes                 float64
media_type             object
posts_count           float64
followers             float64
is_verified           float64
datetime              float64
image_url              object
url                    object
comments              float64
thumbnails             object
location               object
dtype: object

In [11]:
string_columns=['biography', 'caption']

In [12]:
df.shape

(44159, 20)

##Emoji replacement

In [ ]:
#To be run for other instagram datasets 
# for i in string_columns:
#   emojis_replacement(df[i])

In [13]:
pip install emot

Collecting emot
  Downloading emot-3.1-py3-none-any.whl (61 kB)
     |‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 61 kB 15 kB/s
Installing collected packages: emot
Successfully installed emot-3.1

In [14]:
import re
import pickle
#from emot.emo_unicode import UNICODE_EMO, EMOTICONS
from emot.emo_unicode import UNICODE_EMOJI # For emojis
from emot.emo_unicode import EMOTICONS_EMO # For EMOTICONS

with open('Emoji_Dict.p', 'rb') as fp:
    Emoji_Dict = pickle.load(fp)
Emoji_Dict = {v: k for k, v in Emoji_Dict.items()}

def convert_emojis_to_word(text):
    for emot in Emoji_Dict:
        text = re.sub(r'('+emot+')', "_".join(Emoji_Dict[emot].replace(",","").replace(":","").split()), text)
    return text

#text = "I won ü•á in üèè"
#convert_emojis_to_word(text)

In [18]:
#Just to see if it works fine
convert_emojis_to_word(df['biography'][1])

'globe_showing_Americasüß≥fire1st_place_medalartist_palettewine_glasshot_beverage\n          üáªüá™  üá®üá¥\nEMPRESARIO SO√ëADOR\n@alexpintoarte\n@ileinktattoostudio\n@microcapillum'

In [17]:
df.biography

0                                                      NaN
1        üåéüß≥üî•ü•áüé®üç∑‚òï\n          üáªüá™  üá®üá¥\nEMPRESARIO SO√ëADOR\...
2                                                      NaN
3            Consultant Plastic and Reconstructive Surgeon
4                                                      NaN
                               ...
44154    Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...
44155    Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...
44156    Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...
44157    Consultant Plastic Surgeon\n‚ñ™Ô∏èLondon, U.K. \nüì©...
44158                                                  NaN
Name: biography, Length: 44159, dtype: object

In [22]:
#It takes 1h36 min to run. No need to compile again. The result is stored in a new dataset 'data_with_converted_emojis_bio.csv'
df.biography=df.biography.map(lambda x : convert_emojis_to_word(str(x)))

In [23]:
df.head()

,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,likes,media_type,posts_count,followers,is_verified,datetime,image_url,url,comments,thumbnails,location
0,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,globe_showing_Americasüß≥fire1st_place_medalarti...,3.654414e+09,NaN,NaN,1105.0,NaN,NaN,515.0,1244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,NaN,NaN,8.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.to_csv('data_with_converted_emojis_bio.csv', encoding='utf-8')

In [28]:
df=pd.read_csv('data_with_converted_emojis_bio.csv', encoding='utf-8')

In [29]:
df.caption=df.caption.map(lambda x : convert_emojis_to_word(str(x)))

In [30]:
df.to_csv('data_with_converted_emojis_cap.csv', encoding='utf-8')

In [31]:
df=pd.read_csv('data_with_converted_emojis_bio.csv', encoding='utf-8')

##Creation of Hashtags

In [32]:
df["hashtags"] = df.caption.apply(lambda x: [x for x in str(x).split(" ") if x.startswith("#")])

##Text Lower

In [33]:
df.apply(lambda x: x.astype(str).str.lower())
df

,Unnamed: 0,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,...,posts_count,followers,is_verified,datetime,image_url,url,comments,thumbnails,location,hashtags
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
1,1,NaN,NaN,NaN,NaN,globe_showing_Americasüß≥fire1st_place_medalarti...,3.654414e+09,NaN,NaN,1105.0,...,515.0,1244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
3,3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,...,8.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44154,44154,drdariushnikkhah,Finalising the 50 chapters of an exciting book...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.648973e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,136.0,1124.0,NaN,1.630002e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTDCnYcqSBP/,6.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom",[]
44155,44155,drdariushnikkhah,At Harefield heart ‚ù§Ô∏è hospital - probably only...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.647971e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,136.0,1124.0,NaN,1.629883e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS_e1ntq-Qo/,3.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....",NaN,[]
44156,44156,drdariushnikkhah,Great to be back at the first face to face sci...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.659552e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,136.0,1124.0,NaN,1.631263e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTooI4TK0sF/,0.0,"[{""src"":""https://scontent-lhr8-1.cdninstagram....","Oxford, Oxfordshire",[]
44157,44157,drdariushnikkhah,Before and after of a bilateral breast reducti...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.646593e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,136.0,1124.0,NaN,1.629718e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS6lisWKX4k/,7.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom","[#plasticsurgery, #breastsurgery, #breastreduc..."
44158,44158,drdariushnikkhah,Local anaesthetic flexor tendon repair is a sa...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[#wideawakehandsurgery, #walant, #flexortendon..."

##Remove punctuation

In [34]:
df["biography_wo_punc"] = df["biography"].str.replace('[{}]'.format(string.punctuation), '')
df["caption_wo_punc"] = df["caption"].str.replace('[{}]'.format(string.punctuation), '')
df["profile_wo_punc"] = df["profile_name"].str.replace('[{}]'.format(string.punctuation), '')
# df["tokens_wo_punc"] = df["tokens"].str.replace('[{}]'.format(string.punctuation), '')

df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until

,Unnamed: 0,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,...,datetime,image_url,url,comments,thumbnails,location,hashtags,biography_wo_punc,caption_wo_punc,profile_wo_punc
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,globe_showing_Americasüß≥fire1st_place_medalarti...,3.654414e+09,NaN,NaN,1105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,[],globeshowingAmericasüß≥fire1stplacemedalartistpa...,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,[],Consultant Plastic and Reconstructive Surgeon,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44154,44154,drdariushnikkhah,Finalising the 50 chapters of an exciting book...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.648973e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,1.630002e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTDCnYcqSBP/,6.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom",[],Consultant Plastic Surgeon\nblacksmallsquareÔ∏èL...,Finalising the 50 chapters of an exciting book...,Mr Dariush Nikkhah FRCSPlast
44155,44155,drdariushnikkhah,At Harefield heart ‚ù§Ô∏è hospital - probably only...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.647971e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,1.629883e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS_e1ntq-Qo/,3.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....",NaN,[],Consultant Plastic Surgeon\nblacksmallsquareÔ∏èL...,At Harefield heart ‚ù§Ô∏è hospital probably only ...,Mr Dariush Nikkhah FRCSPlast
44156,44156,drdariushnikkhah,Great to be back at the first face to face sci...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.659552e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,1.631263e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTooI4TK0sF/,0.0,"[{""src"":""https://scontent-lhr8-1.cdninstagram....","Oxford, Oxfordshire",[],Consultant Plastic Surgeon\nblacksmallsquareÔ∏èL...,Great to be back at the first face to face sci...,Mr Dariush Nikkhah FRCSPlast
44157,44157,drdariushnikkhah,Before and after of a bilateral breast reducti...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.646593e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,1.629718e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS6lisWKX4k/,7.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom","[#plasticsurgery, #breastsurgery, #breastreduc...",Consultant Plastic Surgeon\nblacksmallsquareÔ∏èL...,Before and after of a bilateral breast reducti...,Mr Dariush Nikkhah FRCSPlast
44158,44158,drdariushnikkhah,Local anaesthetic flexor tendon repair is a sa...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[#wideawakehandsurgery, #walant, #flexortendon...",NaN,Local anaesthetic flexor tendon repair is a sa...,Mr Dariush Nikkhah FRCSPlast

In [35]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [36]:
df["biography_wo_stop"] = df["biography_wo_punc"].apply(lambda text: remove_stopwords(text))
df["caption_wo_stop"] = df["caption_wo_punc"].apply(lambda text: remove_stopwords(text))
df["profile_wo_stop"] = df["profile_wo_punc"].apply(lambda text: remove_stopwords(text))
# df["tokens_wo_stop"] = df["tokens_wo_punc"].apply(lambda text: remove_stopwords(text))

##Removal of frequent words

In [37]:
from collections import Counter
cnt = Counter()
for text in df["biography_wo_stop"].values:
    for word in text.split():
        cnt[word] += 1
        
cnt.most_common(10)

[('London', 5395),
 ('The', 4058),
 ('heart', 3748),
 ('Plastic', 3476),
 ('Surgeon', 3373),
 ('link', 3299),
 ('hotel', 3072),
 ('A', 3041),
 ('Open', 3025),
 ('roundpushpin', 2619)]

In [38]:
FREQWORDS = set([w for (w, wc) in cnt.most_common(10)])
# def remove_freqwords(text):
#     """custom function to remove the frequent words"""
#     return " ".join([word for word in str(text).split() if word not in FREQWORDS])

df["biography_wo_stopfreq"] = df["biography_wo_stop"].apply(lambda text: remove_freqwords(text))
df["caption_wo_stopfreq"] = df["caption_wo_stop"].apply(lambda text: remove_freqwords(text))
df["profile_wo_stopfreq"] = df["profile_wo_stop"].apply(lambda text: remove_freqwords(text))
# df["tokens_wo_stopfreq"] = df["tokens_wo_stop"].apply(lambda text: remove_freqwords(text))

df.head()

,Unnamed: 0,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,...,hashtags,biography_wo_punc,caption_wo_punc,profile_wo_punc,biography_wo_stop,caption_wo_stop,profile_wo_stop,biography_wo_stopfreq,caption_wo_stopfreq,profile_wo_stopfreq
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,[],NaN,NaN,NaN,nan,nan,nan,nan,nan,nan
1,1,NaN,NaN,NaN,NaN,globe_showing_Americasüß≥fire1st_place_medalarti...,3.654414e+09,NaN,NaN,1105.0,...,[],globeshowingAmericasüß≥fire1stplacemedalartistpa...,NaN,NaN,globeshowingAmericasüß≥fire1stplacemedalartistpa...,nan,nan,globeshowingAmericasüß≥fire1stplacemedalartistpa...,nan,nan
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,[],NaN,NaN,NaN,nan,nan,nan,nan,nan,nan
3,3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,...,[],Consultant Plastic and Reconstructive Surgeon,NaN,NaN,Consultant Plastic Reconstructive Surgeon,nan,nan,Consultant Reconstructive,nan,nan
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,[],NaN,NaN,NaN,nan,nan,nan,nan,nan,nan

##removal of rare words

In [39]:

n_rare_words = 10
RAREWORDS = set([w for (w, wc) in cnt.most_common()[:-n_rare_words-1:-1]])

In [40]:
df["biography_wo_stopfreqrare"] = df["biography_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
df["caption_wo_stopfreqrare"] = df["caption_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
df["profile_wo_stopfreqrare"] = df["profile_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
# df["tokens_wo_stopfreqrare"] = df["tokens_wo_stopfreq"].apply(lambda text: remove_rarewords(text))

df.head()

,Unnamed: 0,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,...,profile_wo_punc,biography_wo_stop,caption_wo_stop,profile_wo_stop,biography_wo_stopfreq,caption_wo_stopfreq,profile_wo_stopfreq,biography_wo_stopfreqrare,caption_wo_stopfreqrare,profile_wo_stopfreqrare
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,1,NaN,NaN,NaN,NaN,globe_showing_Americasüß≥fire1st_place_medalarti...,3.654414e+09,NaN,NaN,1105.0,...,NaN,globeshowingAmericasüß≥fire1stplacemedalartistpa...,nan,nan,globeshowingAmericasüß≥fire1stplacemedalartistpa...,nan,nan,globeshowingAmericasüß≥fire1stplacemedalartistpa...,nan,nan
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,...,NaN,Consultant Plastic Reconstructive Surgeon,nan,nan,Consultant Reconstructive,nan,nan,Consultant Reconstructive,nan,nan
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan

##Stemming

In [ ]:
# from nltk.stem.porter import PorterStemmer

# stemmer = PorterStemmer()
# def stem_words(text):
#     return " ".join([stemmer.stem(word) for word in text.split()])

In [41]:
df["biography_stemmed"] = df["biography_wo_stopfreqrare"].apply(lambda text: stem_words(text))
df["caption_stemmed"] = df["caption_wo_stopfreqrare"].apply(lambda text: stem_words(text))
# df["profile_stemmed"] = df["profile_wo_punc"].str.apply(lambda text: stem_words(text))
# df["tokens_stemmed"] = df["tokens_wo_punc"].apply(lambda text: stem_words(text))

##Lemmatization

In [42]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [43]:
from nltk.stem import WordNetLemmatizer

# lemmatizer = WordNetLemmatizer()
# def lemmatize_words(text):
#     return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["biography_final"] = df["biography_stemmed"].apply(lambda text: lemmatize_words(text))
df["caption_final"] = df["caption_stemmed"].apply(lambda text: lemmatize_words(text))
df["profile_final"] = df["profile_wo_stopfreqrare"].apply(lambda text: lemmatize_words(text))
# df["tokens_final"] = df["tokens_stemmed"].apply(lambda text: lemmatize_words(text))

df.head()

,Unnamed: 0,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,...,caption_wo_stopfreq,profile_wo_stopfreq,biography_wo_stopfreqrare,caption_wo_stopfreqrare,profile_wo_stopfreqrare,biography_stemmed,caption_stemmed,biography_final,caption_final,profile_final
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,1,NaN,NaN,NaN,NaN,globe_showing_Americasüß≥fire1st_place_medalarti...,3.654414e+09,NaN,NaN,1105.0,...,nan,nan,globeshowingAmericasüß≥fire1stplacemedalartistpa...,nan,nan,globeshowingamericasüß≥fire1stplacemedalartistpa...,nan,globeshowingamericasüß≥fire1stplacemedalartistpa...,nan,nan
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,...,nan,nan,Consultant Reconstructive,nan,nan,consult reconstruct,nan,consult reconstruct,nan,nan
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

##Removal of URLs

In [44]:
df['biography_final'] = df['biography_final'].apply(lambda x: re.split('https:\/\/.*', str(x))[0])
df['caption_final'] = df['caption_final'].apply(lambda x: re.split('https:\/\/.*', str(x))[0])
df

,Unnamed: 0,account,caption,profile_name,profile_image_link,biography,id,business_email,external_url,following,...,caption_wo_stopfreq,profile_wo_stopfreq,biography_wo_stopfreqrare,caption_wo_stopfreqrare,profile_wo_stopfreqrare,biography_stemmed,caption_stemmed,biography_final,caption_final,profile_final
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,1,NaN,NaN,NaN,NaN,globe_showing_Americasüß≥fire1st_place_medalarti...,3.654414e+09,NaN,NaN,1105.0,...,nan,nan,globeshowingAmericasüß≥fire1stplacemedalartistpa...,nan,nan,globeshowingamericasüß≥fire1stplacemedalartistpa...,nan,globeshowingamericasüß≥fire1stplacemedalartistpa...,nan,nan
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,3,NaN,NaN,NaN,NaN,Consultant Plastic and Reconstructive Surgeon,1.366797e+09,NaN,http://www.psauk.org/,57.0,...,nan,nan,Consultant Reconstructive,nan,nan,consult reconstruct,nan,consult reconstruct,nan,nan
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44154,44154,drdariushnikkhah,Finalising the 50 chapters of an exciting book...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.648973e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,Finalising 50 chapters exciting book due relea...,Mr Dariush Nikkhah FRCSPlast,Consultant blacksmallsquareÔ∏èLondon UK envelope...,Finalising 50 chapters exciting book due relea...,Mr Dariush Nikkhah FRCSPlast,consult blacksmallsquareÔ∏èlondon UK envelopewit...,finalis 50 chapter excit book due releas year ...,consult blacksmallsquareÔ∏èlondon UK envelopewit...,finalis 50 chapter excit book due releas year ...,Mr Dariush Nikkhah FRCSPlast
44155,44155,drdariushnikkhah,At Harefield heart ‚ù§Ô∏è hospital - probably only...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.647971e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,At Harefield ‚ù§Ô∏è hospital probably hospital I k...,Mr Dariush Nikkhah FRCSPlast,Consultant blacksmallsquareÔ∏èLondon UK envelope...,At Harefield ‚ù§Ô∏è hospital probably hospital I k...,Mr Dariush Nikkhah FRCSPlast,consult blacksmallsquareÔ∏èlondon UK envelopewit...,At harefield ‚ù§Ô∏è hospit probabl hospit I know s...,consult blacksmallsquareÔ∏èlondon UK envelopewit...,At harefield ‚ù§Ô∏è hospit probabl hospit I know s...,Mr Dariush Nikkhah FRCSPlast
44156,44156,drdariushnikkhah,Great to be back at the first face to face sci...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.659552e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,Great back first face face scientific meeting ...,Mr Dariush Nikkhah FRCSPlast,Consultant blacksmallsquareÔ∏èLondon UK envelope...,Great back first face face scientific meeting ...,Mr Dariush Nikkhah FRCSPlast,consult blacksmallsquareÔ∏èlondon UK envelopewit...,great back first face face scientif meet 2 yea...,consult blacksmallsquareÔ∏èlondon UK envelopewit...,great back first face face scientif meet 2 yea...,Mr Dariush Nikkhah FRCSPlast
44157,44157,drdariushnikkhah,Before and after of a bilateral breast reducti...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,Consultant Plastic Surgeon\nblack_small_square...,2.646593e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,...,Before bilateral breast reduction procedure I ...,Mr Dariush Nikkhah FRCSPlast,Consultant blacksmallsquareÔ∏èLondon UK envelope...,Before bilateral breast reduction procedure I ...,Mr Dariush Nikkhah FRCSPlast,consult blacksmallsquareÔ∏èlondon UK envelopewit...,befor bilater breast reduct procedur I perform...,consult blacksmallsquareÔ∏èlondon UK envelopewit...,befor bilater breast reduct procedur I perform...,Mr Dariush Nikkhah FRCSPlast
44158,44158,drdariushnikkhah,Local anaesthetic flexor tendon repair is a sa...,Mr Dariush Nikkhah FRCS(Plast),https://scontent-lhr8-1.cdninstagram.com/v/t51...,NaN,NaN,NaN,NaN,NaN,...,Local anaesthetic flexor tendon repair safe ef...,Mr Dariush Nikkhah FRCSPlast,nan,Local anaesthetic flexor tendon repair safe ef...,Mr Dariush Nikkhah FRCSPlast,nan,local anaesthet flexor tendon repair safe effe...,nan,local anaesthet flexor tendon repair safe effe...,Mr Dariush Nikkhah FRCSPlast

#Final dataframe

In [45]:
df_final=df.drop(['biography','caption', 'profile_name', 'biography_wo_punc',	'caption_wo_punc'	,'biography_wo_stop',	'caption_wo_stop',	'profile_wo_punc'	,'profile_wo_stop'	,'biography_wo_stopfreq',	'caption_wo_stopfreq'	,'profile_wo_stopfreq','biography_wo_stopfreqrare'	,'caption_wo_stopfreqrare',	'profile_wo_stopfreqrare'	,'biography_stemmed'	,'caption_stemmed'], axis=1)
df_final

,Unnamed: 0,account,profile_image_link,id,business_email,external_url,following,likes,media_type,posts_count,...,datetime,image_url,url,comments,thumbnails,location,hashtags,biography_final,caption_final,profile_final
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
1,1,NaN,NaN,3.654414e+09,NaN,NaN,1105.0,NaN,NaN,515.0,...,NaN,NaN,NaN,NaN,NaN,NaN,[],globeshowingamericasüß≥fire1stplacemedalartistpa...,nan,nan
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
3,3,NaN,NaN,1.366797e+09,NaN,http://www.psauk.org/,57.0,NaN,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,[],consult reconstruct,nan,nan
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44154,44154,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.648973e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,137.0,Image,136.0,...,1.630002e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTDCnYcqSBP/,6.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom",[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,finalis 50 chapter excit book due releas year ...,Mr Dariush Nikkhah FRCSPlast
44155,44155,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.647971e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,83.0,Image,136.0,...,1.629883e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS_e1ntq-Qo/,3.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....",NaN,[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,At harefield ‚ù§Ô∏è hospit probabl hospit I know s...,Mr Dariush Nikkhah FRCSPlast
44156,44156,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.659552e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,75.0,Carousel,136.0,...,1.631263e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTooI4TK0sF/,0.0,"[{""src"":""https://scontent-lhr8-1.cdninstagram....","Oxford, Oxfordshire",[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,great back first face face scientif meet 2 yea...,Mr Dariush Nikkhah FRCSPlast
44157,44157,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.646593e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,77.0,Image,136.0,...,1.629718e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS6lisWKX4k/,7.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom","[#plasticsurgery, #breastsurgery, #breastreduc...",consult blacksmallsquareÔ∏èlondon UK envelopewit...,befor bilater breast reduct procedur I perform...,Mr Dariush Nikkhah FRCSPlast
44158,44158,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[#wideawakehandsurgery, #walant, #flexortendon...",nan,local anaesthet flexor tendon repair safe effe...,Mr Dariush Nikkhah FRCSPlast

In [46]:
df_final

,Unnamed: 0,account,profile_image_link,id,business_email,external_url,following,likes,media_type,posts_count,...,datetime,image_url,url,comments,thumbnails,location,hashtags,biography_final,caption_final,profile_final
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
1,1,NaN,NaN,3.654414e+09,NaN,NaN,1105.0,NaN,NaN,515.0,...,NaN,NaN,NaN,NaN,NaN,NaN,[],globeshowingamericasüß≥fire1stplacemedalartistpa...,nan,nan
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
3,3,NaN,NaN,1.366797e+09,NaN,http://www.psauk.org/,57.0,NaN,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,[],consult reconstruct,nan,nan
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44154,44154,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.648973e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,137.0,Image,136.0,...,1.630002e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTDCnYcqSBP/,6.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom",[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,finalis 50 chapter excit book due releas year ...,Mr Dariush Nikkhah FRCSPlast
44155,44155,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.647971e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,83.0,Image,136.0,...,1.629883e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS_e1ntq-Qo/,3.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....",NaN,[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,At harefield ‚ù§Ô∏è hospit probabl hospit I know s...,Mr Dariush Nikkhah FRCSPlast
44156,44156,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.659552e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,75.0,Carousel,136.0,...,1.631263e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTooI4TK0sF/,0.0,"[{""src"":""https://scontent-lhr8-1.cdninstagram....","Oxford, Oxfordshire",[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,great back first face face scientif meet 2 yea...,Mr Dariush Nikkhah FRCSPlast
44157,44157,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.646593e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,77.0,Image,136.0,...,1.629718e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS6lisWKX4k/,7.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom","[#plasticsurgery, #breastsurgery, #breastreduc...",consult blacksmallsquareÔ∏èlondon UK envelopewit...,befor bilater breast reduct procedur I perform...,Mr Dariush Nikkhah FRCSPlast
44158,44158,drdariushnikkhah,https://scontent-lhr8-1.cdninstagram.com/v/t51...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[#wideawakehandsurgery, #walant, #flexortendon...",nan,local anaesthet flexor tendon repair safe effe...,Mr Dariush Nikkhah FRCSPlast

In [52]:
df_final.drop(['account'], axis=1, inplace=True)
df_final.drop(['Unnamed: 0'], axis=1, inplace=True)

In [53]:
# old_names = [ 'input_account', 'biography_final', 'caption_final', 'profile_final'] 
# new_names = {'account', 'biography', 'caption', 'profile'}
# df_final.columns=new_names


df = df_final.rename(columns={'input_account': 'account','biography_final':'biography','caption_final':'caption','profile_final':'profile'})

In [54]:
df

,profile_image_link,id,business_email,external_url,following,likes,media_type,posts_count,followers,is_verified,datetime,image_url,url,comments,thumbnails,location,hashtags,biography,caption,profile
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
1,NaN,3.654414e+09,NaN,NaN,1105.0,NaN,NaN,515.0,1244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],globeshowingamericasüß≥fire1stplacemedalartistpa...,nan,nan
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
3,NaN,1.366797e+09,NaN,http://www.psauk.org/,57.0,NaN,NaN,8.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],consult reconstruct,nan,nan
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44154,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.648973e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,137.0,Image,136.0,1124.0,NaN,1.630002e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTDCnYcqSBP/,6.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom",[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,finalis 50 chapter excit book due releas year ...,Mr Dariush Nikkhah FRCSPlast
44155,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.647971e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,83.0,Image,136.0,1124.0,NaN,1.629883e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS_e1ntq-Qo/,3.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....",NaN,[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,At harefield ‚ù§Ô∏è hospit probabl hospit I know s...,Mr Dariush Nikkhah FRCSPlast
44156,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.659552e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,75.0,Carousel,136.0,1124.0,NaN,1.631263e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CTooI4TK0sF/,0.0,"[{""src"":""https://scontent-lhr8-1.cdninstagram....","Oxford, Oxfordshire",[],consult blacksmallsquareÔ∏èlondon UK envelopewit...,great back first face face scientif meet 2 yea...,Mr Dariush Nikkhah FRCSPlast
44157,https://scontent-lhr8-1.cdninstagram.com/v/t51...,2.646593e+18,NaN,https://www.plasticreconsurg.co.uk/,299.0,77.0,Image,136.0,1124.0,NaN,1.629718e+12,j_kzvc99wm2q4pjru5kn.c8774cb5509196a5a43b8ebc2...,https://www.instagram.com/p/CS6lisWKX4k/,7.0,"[{""src"":""https://scontent-lhr8-2.cdninstagram....","London, United Kingdom","[#plasticsurgery, #breastsurgery, #breastreduc...",consult blacksmallsquareÔ∏èlondon UK envelopewit...,befor bilater breast reduct procedur I perform...,Mr Dariush Nikkhah FRCSPlast
44158,https://scontent-lhr8-1.cdninstagram.com/v/t51...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[#wideawakehandsurgery, #walant, #flexortendon...",nan,local anaesthet flexor tendon repair safe effe...,Mr Dariush Nikkhah FRCSPlast

In [55]:
df.to_csv('after_preprocessing.csv', encoding='utf-8')