In [137]:
# #To be run in further steps
# import gensim.downloader 
# import ast

# # Show all available models in gensim-data
# print(list(gensim.downloader.info()['models'].keys()))
# model = gensim.downloader.load('word2vec-google-news-300')

In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import spacy
import string

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [11]:
!cp gdrive/MyDrive/GitHub/NLP-project-/preprocessing_functions.py .

In [12]:
!python preprocessing_functions.py

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [15]:
execfile('preprocessing_functions.py')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [5]:
#df = pd.read_csv('NLP_project_kickoff_data.csv', encoding='utf-8')
df = pd.read_csv('NLP_project_kickoff_data.csv', encoding='utf-8')

In [ ]:
df.head()

In [6]:
df_emo= pd.read_csv('emojis.csv')

##Emoji replacement

In [16]:
string_columns=['biography', 'caption', 'tokens']

In [17]:

for i in string_columns:
  emojis_replacement(df[i])  
  lower_columns(i)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

KeyError: ignored

In [ ]:
df

##Text Lower

In [18]:
lower_columns('biography')
lower_column('caption')
lower_column('tokens')

KeyError: ignored

##Remove punctuation

In [ ]:
df.head()

In [20]:
df["biography_wo_punc"] = df["biography"].apply(lambda text: remove_punctuation(text))
#df["caption_wo_punc"] = df["caption"].apply(lambda text: remove_punctuation(text)) #not working
#df["profile_name"] = df["profile_name"].apply(lambda text: remove_punctuation(text)) #not working
df["tokens_wo_punc"] = df["tokens"].apply(lambda text: remove_punctuation(text))


df.head()

   Unnamed: 0  ...                                  biography_wo_punc
0           0  ...                                                nan
1           1  ...  Facial Cosmetics ENT and Thyroid Clinic by Mr ...
2           2  ...  Facial Cosmetics ENT and Thyroid Clinic by Mr ...
3           3  ...  Facial Cosmetics ENT and Thyroid Clinic by Mr ...
4           4  ...  Jglobe4  London UK\r\nNbuilding6  Cofounder th...

[5 rows x 27 columns]

In [ ]:
pip install --upgrade nltk

In [ ]:
pip install  --upgrade gensim --pre

In [ ]:
!pip install --upgrade gensim

In [21]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
df["biography_wo_stop"] = df["biography"].apply(lambda text: remove_stopwords(text))
df.head()

   Unnamed: 0  ...                                  biography_wo_stop
0           0  ...                                                nan
1           1  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
2           2  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
3           3  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
4           4  ...  Jglobe4 London, UK Nbuilding6 Co-founder @thep...

[5 rows x 28 columns]

#Removal of frequent words

In [23]:
from collections import Counter
cnt = Counter()
for text in df["biography_wo_stop"].values:
    for word in text.split():
        cnt[word] += 1
        
cnt.most_common(10)

[('&', 166),
 ('based', 125),
 ('Enhancing', 104),
 ('ð\x8f—¡ð\x8f—®ð\x8f˜\x8fð\x8f˜‚ð\x8f—¿ð\x8f—®ð\x8f—¹', 104),
 ('ð\x8f—•ð\x8f—²ð\x8f—®ð\x8f˜‚ð\x8f˜\x8fð\x8f˜†', 104),
 ('ðŸŒ¥', 104),
 ('@officialnavyprofessional', 104),
 ('Educator-', 104),
 ('discount', 104),
 ('AUD10', 104)]

In [24]:
FREQWORDS = set([w for (w, wc) in cnt.most_common(10)])
# def remove_freqwords(text):
#     """custom function to remove the frequent words"""
#     return " ".join([word for word in str(text).split() if word not in FREQWORDS])

df["biography_wo_stopfreq"] = df["biography_wo_stop"].apply(lambda text: remove_freqwords(text))
df.head()

   Unnamed: 0  ...                              biography_wo_stopfreq
0           0  ...                                                nan
1           1  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
2           2  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
3           3  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
4           4  ...  Jglobe4 London, UK Nbuilding6 Co-founder @thep...

[5 rows x 29 columns]

#removal of rare words

In [25]:

n_rare_words = 10
RAREWORDS = set([w for (w, wc) in cnt.most_common()[:-n_rare_words-1:-1]])

In [26]:
df["biography_wo_stopfreqrare"] = df["biography_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
df.head()

   Unnamed: 0  ...                          biography_wo_stopfreqrare
0           0  ...                                                nan
1           1  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
2           2  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
3           3  ...  Facial Cosmetics, ENT Thyroid Clinic Mr. Mrina...
4           4  ...  Jglobe4 London, UK Nbuilding6 Co-founder @thep...

[5 rows x 30 columns]

#Stemming

In [ ]:
# from nltk.stem.porter import PorterStemmer

# stemmer = PorterStemmer()
# def stem_words(text):
#     return " ".join([stemmer.stem(word) for word in text.split()])

In [27]:
df["biography_stemmed"] = df["biography_wo_punc"].apply(lambda text: stem_words(text))
df.head()

   Unnamed: 0  ...                                  biography_stemmed
0           0  ...                                                nan
1           1  ...  facial cosmet ent and thyroid clinic by Mr mri...
2           2  ...  facial cosmet ent and thyroid clinic by Mr mri...
3           3  ...  facial cosmet ent and thyroid clinic by Mr mri...
4           4  ...  jglobe4 london UK nbuilding6 cofound theplasti...

[5 rows x 31 columns]

In [28]:
from nltk.stem.snowball import SnowballStemmer
SnowballStemmer.languages

('arabic',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'hungarian',
 'italian',
 'norwegian',
 'porter',
 'portuguese',
 'romanian',
 'russian',
 'spanish',
 'swedish')

#Lemmatization

In [29]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [30]:
from nltk.stem import WordNetLemmatizer

# lemmatizer = WordNetLemmatizer()
# def lemmatize_words(text):
#     return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["biography_lemm"] = df["biography_stemmed"].apply(lambda text: lemmatize_words(text))
df.head()

   Unnamed: 0  ...                                     biography_lemm
0           0  ...                                                nan
1           1  ...  facial cosmet ent and thyroid clinic by Mr mri...
2           2  ...  facial cosmet ent and thyroid clinic by Mr mri...
3           3  ...  facial cosmet ent and thyroid clinic by Mr mri...
4           4  ...  jglobe4 london UK nbuilding6 cofound theplasti...

[5 rows x 32 columns]

#Removal of URLs

In [31]:
df['biography_wo_urls']=df['biography_lemm'].apply(remove_urls)
df

     Unnamed: 0  ...                                  biography_wo_urls
0             0  ...                                                nan
1             1  ...  facial cosmet ent and thyroid clinic by Mr mri...
2             2  ...  facial cosmet ent and thyroid clinic by Mr mri...
3             3  ...  facial cosmet ent and thyroid clinic by Mr mri...
4             4  ...  jglobe4 london UK nbuilding6 cofound theplasti...
..          ...  ...                                                ...
514           0  ...       lcomput liphon lmusic8 lgame2 âš½â˜•ðÿ»ðÿ•
515           1  ...       lcomput liphon lmusic8 lgame2 âš½â˜•ðÿ»ðÿ•
516           2  ...       lcomput liphon lmusic8 lgame2 âš½â˜•ðÿ»ðÿ•
517           0  ...       lcomput liphon lmusic8 lgame2 âš½â˜•ðÿ»ðÿ•
518           1  ...       lcomput liphon lmusic8 lgame2 âš½â˜•ðÿ»ðÿ•

[519 rows x 33 columns]

#Removal of HTML tags

In [32]:
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)

Lcomputer Liphone Lmusic8 Lgame2 âš½â˜•ðŸ»ðŸ•